export const productData = [
    {
        id:1,
        title:"SS & Glass Handrails",
        thumbnail:'/images/product/1.png',
        price:"1099",
        discount_price:"999",
    },
    {
        id:2,
        title:" Aluminum Curtain Wall",
        thumbnail:'/images/product/2.png',
        price:"259",
        discount_price:"199",
    },
    {
        id:3,
        title:"Stailess Steel Cladded Doors",
        thumbnail:'/images/product/3.png',
        price:"299",
        discount_price:"198",
    },
    {
        id:4,
        title:"Stinless Steel Handrails",
        thumbnail:'/images/product/4.png',
        price:"459",
        discount_price:"358",
    },
    {
        id:5,
        title:"Aluminum Doors & Window",
        thumbnail:'/images/product/5.png',
        price:"299",
        discount_price:"198",
    },
    {
        id:6,
        title:"Fire Rated Steel Doors",
        thumbnail:'/images/product/6.png',
        price:"459",
        discount_price:"358",
    },
    {
        id:7,
        title:"Mashrabiya",
        thumbnail:'/images/product/7.png',
        price:"1099",
        discount_price:"999",
    },
    {
        id:8,
        title:"Steel Powder Coated Handrail",
        thumbnail:'/images/product/8.png',
        price:"259",
        discount_price:"199",
    },
    {
        id:9,
        title:"Signage Board",
        thumbnail:'/images/product/9.png',
        price:"299",
        discount_price:"198",
    },
    {
        id:10,
        title:" ACP-Cladding",
        thumbnail:'/images/product/10.png',
        price:"459",
        discount_price:"358",
    },
    {
        id:11,
        title:"Steel Works",
        thumbnail:'/images/product/11.png',
        price:"299",
        discount_price:"198",
    },
    {
        id:12,
        title:"Glass Balustrade",
        thumbnail:'/images/product/12.png',
        price:"459",
        discount_price:"358",
    },
    {
        id:13,
        title:"Glass Partitions",
        thumbnail:'/images/product/13.png',
        price:"459",
        discount_price:"358",
    },
    {
        id:14,
        title:"Aluminum Louver",
        thumbnail:'/images/product/14.png',
        price:"459",
        discount_price:"358",
    },
    {
        id:15,
        title:"Steel Fence",
        thumbnail:'/images/product/15.png',
        price:"459",
        discount_price:"358",
    },
]